/// <reference types="vite/client" />
declare const __APP_VERSION__: string;
declare const __APP_NAME__: string;
declare const __APP_DESCRIPTION__: string;
declare const __DEFAULT_IRC_SERVER__: string;
declare const __DEFAULT_IRC_SERVER_NAME__: string;
declare const __DEFAULT_IRC_CHANNELS__: string[];
declare const __HIDE_SERVER_LIST__: boolean;
declare const __BACKEND_URL__: string;
